<Project Sdk="Microsoft.NET.Sdk">

  <!-- Global Properties -->
  <PropertyGroup>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>

    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

</Project>